export const getHomePath = () => '/'
export const getNewPropertyPath = () => '/property/add'
export const getLoginPath = () => '/login'
export const getLogoutPath = () => '/logout'
export const getRegisterPath = () => '/signup'
